version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  neo4j:
    driver: ${VOLUMES_DRIVER}

services:
  ### Neo4j ################################################
  neo4j:
    image: neo4j:3.5.26
    volumes:
      - ${DATA_PATH_HOST}/neo4j/conf:/var/lib/neo4j/conf
      - ${DATA_PATH_HOST}/neo4j/mnt:/var/lib/neo4j/import
      - ${DATA_PATH_HOST}/neo4j/plugins:/plugins
      - ${DATA_PATH_HOST}/neo4j/data:/data
      - ${DATA_PATH_HOST}/neo4j/logs:/var/lib/neo4j/logs
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_AUTH=neo4j/123456  #修改默认用户密码
    networks:
      - backend
